name: build-test-workflow
on: 
  push:
    branches-ignore:
      - "master"
jobs:
  build-test:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cache/repo-cache
            ~/.cache/bazel
          key: ${{ runner.os }}-inline-java-bazel

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .bazelrc
        run: |
            rm -rf /home/runner/.cache/bazel/_bazel_runner/2c59ef6553368b7f5137b41540403b36/external/rules_haskell_ghc_nixpkgs/bin/ghc
            echo "Setup .bazelrc.local"
            echo "build --bes_results_url=https://app.buildbuddy.io/invocation/" > ${{ github.workspace }}/.bazelrc.local
            echo "build --bes_backend=grpcs://cloud.buildbuddy.io" >> ${{ github.workspace }}/.bazelrc.local
            echo "build --disk_cache=$HOME/.cache/bazel" >> .bazelrc.local

      - name: Prefetch Stackage snapshot
        # Retry if needed due to network flakiness.
        run: |
          nix-shell --pure --run \
            'cmd="bazel fetch @stackage//... --disk_cache=~/.cache/bazel --repository_cache=~/.cache/repo-cache"; $cmd || $cmd || $cmd'

      - name: Build all
        run: |
            nix-shell --pure --run 'bazel build //... --disk_cache=~/.cache/bazel --repository_cache=~/.cache/repo-cache'

      - name: Run tests
        run: |
            nix-shell --pure --run 'bazel test --test_output=all //... '