name: build-test-workflow
on: 
  push:
    branches-ignore:
      - "master"
jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-inline-java-bazel

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.05

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .bazelrc
        run: |
            echo "common --disk_cache=~/.cache/bazel" >> ${{ github.workspace }}/.bazelrc.local

      - name: Prefetch Stackage snapshot
        # Retry if needed due to network flakiness.
        run: |
          nix-shell --pure --run \
            'cmd="bazel fetch @stackage//... --disk_cache=~/.cache/bazel"; $cmd || $cmd || $cmd'

      - name: Build all
        run: |
            nix-shell --pure --run 'bazel build //... --disk_cache=~/.cache/bazel'

      - name: Run tests
        run: |
            nix-shell --pure --run 'bazel test --test_output=all //... --repository_cache=$HOME/.cache/repo-cache --disk_cache=$HOME/.cache/bazel'